[package]
name = "nannou-app-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "*"
nannou_audio = "*"
nannou_egui = "*"
ringbuf = "*"
atomic_float = "*"