[package]
name = "otopoiesis"
version = "0.1.0"
authors = ["Tomoya Matsuura <me@matsuuratomoya.com>"]
edition = "2021"
resolver = "2"
description = "a constructive audio programming environment with timeline-based view"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "otopoiesis"


[dependencies]

nannou_audio = "0.18.0"
# muse use head version to solve ui-overlapping problems.
egui = { version = "0.19.0", git = "https://github.com/emilk/egui", rev = "7133818" }
eframe = { version = "0.19.0", git = "https://github.com/emilk/egui", rev = "7133818" }
# to resolve conflict versions used between egui and nannou_audio(cpal)
web-sys = "0.3.60"
ringbuf = "*"
atomic_float = "*"
serde = { version = "*", features = ["rc"] }
serde_json = "*"
serde_with = "2.1.0"
undo = "0.47.*"
