# Thanks to https://zenn.dev/naokifujita/articles/c890954165c21f

name: cache_cargo
description: caching .cargo directory
runs:
  using: composite
  steps:
    - name: Make Cache for Cargo & npm
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          node_modules
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-cargo-
