on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add rustfmt
      - run: sudo apt-get install -y libasound2-dev libgtk-3-dev librust-atk-dev
      - uses: ./.github/actions/cache_cargo
      - name: fmt
        run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - run: sudo apt-get install -y libasound2-dev libgtk-3-dev librust-atk-dev
      - uses: ./.github/actions/cache_cargo
      - name: clippy
        run: cargo clippy --all-targets -- -D warnings
